name: Windows RTools 3.5

on:
  pull_request:
    branches: [ torsten-develop, torsten-master ]
  push:
    branches: [ torsten-develop ]
    paths-ignore:
      - 'doygen/**'
      - 'hooks/**'
      - 'licenses/**'
      - 'LICENSE.md'
      - 'README.md'
      - 'RELEASE-NOTES.txt'
jobs:
  prim-rev:
    name: prim and rev tests
    runs-on: windows-latest

    steps:
    - uses: n1hility/cancel-previous-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/torsten-master' && github.ref != 'refs/heads/torsten-develop'"

    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-python@v2
      with:
        python-version: '2.x'
    - name: Download RTools
      run: Invoke-WebRequest -Uri https://cran.r-project.org/bin/windows/Rtools/rtools40-x86_64.exe -OutFile ./R40.exe
    - name: Install RTools
      shell: powershell
      run: Start-Process -FilePath ./R40.exe -ArgumentList /VERYSILENT -NoNewWindow -Wait
    - name: PATH Setup
      shell: powershell
      run: echo "C:/Rtools40/bin;C:/Rtools40/mingw_64/bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
    - name: Print g++ & make version and path
      shell: powershell
      run: |
        g++ --version
        Get-Command g++ | Select-Object -ExpandProperty Definition
        mingw32-make --version
        Get-Command mingw32-make | Select-Object -ExpandProperty Definition
    - name: Build Math libs
      shell: powershell
      run: mingw32-make -f make/standalone math-libs
    - name: Add TBB to PATH
      shell: powershell
      run: echo "D:/a/math/math/lib/tbb" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
    - name: Run Torsten unit test
      shell: powershell
      run: |
        python.exe runTests.py -j2 stan/math/torsten/test/unit

    - name: Upload gtest_output xml
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: gtest_outputs_xml
        path: '**/*_test.xml'
