name: Torsten Math tests

on:
  pull_request:
    branches: [ torsten-develop, torsten-master ]
  push:
    branches: [ torsten-develop ]
    paths-ignore:
      - 'doygen/**'
      - 'hooks/**'
      - 'licenses/**'
      - 'LICENSE.md'
      - 'README.md'
      - 'RELEASE-NOTES.txt'
jobs:
  nix:
    name: ubuntu/macos tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: n1hility/cancel-previous-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/torsten-master' && github.ref != 'refs/heads/torsten-develop'"

    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-python@v2
      with:
        python-version: '2.x'
    - name: Print g++ & make version and path
      shell: bash
      run: |
        g++ --version
        make --version
    - name: Build Math libs
      shell: bash
      run: make -j2 -f make/standalone math-libs
    - name: Add TBB to PATH
      shell: bash
      run: echo "./lib/tbb" >> $GITHUB_PATH
    - name: Add Torsten to PATH
      shell: bash
      run: echo "./stan/math/torsten" >> $GITHUB_PATH
    - name: Run Torsten unit test
      shell: bash
      run: |
        python runTests.py -j2 stan/math/torsten/test/unit

    - name: Upload gtest_output xml
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: gtest_outputs_xml
        path: '**/*_test.xml'

#  win:
#    name: windows tests
#    runs-on: windows-latest
#    needs: nix
#
#    steps:
#    - uses: actions/checkout@v2
#      with:
#        submodules: recursive
#    - uses: actions/setup-python@v2
#      with:
#        python-version: '2.x'
#    - name: Download RTools
#      run: Invoke-WebRequest -Uri https://cran.r-project.org/bin/windows/Rtools/rtools40-x86_64.exe -OutFile ./R40.exe
#    - name: Install RTools
#      shell: powershell
#      run: Start-Process -FilePath ./R40.exe -ArgumentList /VERYSILENT -NoNewWindow -Wait
#    - name: PATH Setup
#      shell: powershell
#      run: echo "C:\RTools40\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
#    - name: PATH Setup
#      shell: powershell
#      run: echo "C:\RTools40\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
#    - name: Print g++ version
#      shell: powershell
#      run: g++ --version
#    - name: Print g++ path
#      shell: powershell
#      run: Get-Command g++ | Select-Object -ExpandProperty Definition
#    - name: Print mingw32-make version
#      shell: powershell
#      run: mingw32-make --version
#    - name: Print mingw32-make path
#      shell: powershell
#      run: Get-Command mingw32-make | Select-Object -ExpandProperty Definition
#    - name: Build Math libs
#      shell: powershell
#      run: mingw32-make -f make/standalone math-libs
#    - name: Add TBB to PATH
#      shell: powershell
#      run: echo "D:\a\math\math\lib\tbb" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
#    - name: Run full unit tests
#      shell: powershell
#      run: python runTests.py -j2 stan/math/torsten/test/unit
#    - name: Upload gtest_output xml
#      uses: actions/upload-artifact@v2
#      if: failure()
#      with:
#        name: gtest_outputs_xml
#        path: '**/*_test.xml'
